ALTER TABLE "Post"
  ADD COLUMN IF NOT EXISTS "reactionThumbsUp" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "reactionHeart" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "reactionHope" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "reactionClap" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "Comment"
  ADD COLUMN IF NOT EXISTS "reactionThumbsUp" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "reactionHeart" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "reactionHope" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "reactionClap" INTEGER NOT NULL DEFAULT 0;
